site_name: S1 - Operating instructions
pages:
    - Appearance: appearance_introduction.md
    - Display Area: distribution_of_display_area.md
    - Network Configuration: network_configuration_steps.md
    - Volume Control: volume_control.md
    - Interface Switching: interface_switching.md
    - Terminal Transaction Flow（B To C）: terminal_transaction_process_b2c.md
    - Terminal Transaction Flow（C To B）: terminal_transaction_process_c2b.md
    - Voice Broadcast: voice_broadcast.md
    - About This site: index.md
theme: readthedocs
